-- The Clients table stores basic information about each client.
-- It includes unique identifiers, client names, email addresses, and timestamps for record creation and updates.
-- This table follows normalization principles to separate user profiles from authentication and session management.
CREATE TABLE public."Clients" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- Primary key for the Clients table, auto-generated unique identifier.
  client_name TEXT NULL, -- Name of the client, can be null.
  email TEXT NULL, -- Email address of the client, can be null.
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), -- Timestamp for when the record was created, defaults to the current time.
  update_at TIMESTAMP WITH TIME ZONE NULL, -- Timestamp for the last update of the record, can be null.
  CONSTRAINT Clients_pkey PRIMARY KEY (id), -- Primary key constraint on the "id" column.
  CONSTRAINT Clients_created_at_key UNIQUE (created_at) -- Unique constraint on the "created_at" column.
) TABLESPACE pg_default;

-- The Authentication table stores authentication-related information for clients.
-- This includes hashed passwords, timestamps for creation and updates, and the last login time.
-- A foreign key links this table to the Clients table, ensuring separation of user profiles and authentication data.
CREATE TABLE public."Authentication" ( 
  auth_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- Primary key for the Authentication table, auto-generated unique identifier.
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), -- Timestamp for when the record was created, defaults to the current time.
  password_hash TEXT NULL, -- Stores the hashed password for authentication, can be null.
  last_login TIMESTAMP WITH TIME ZONE NULL, -- Timestamp for the last login of the user, can be null.
  updated_at TIMESTAMP WITH TIME ZONE NULL, -- Timestamp for the last update of the authentication record, can be null.
  client_id BIGINT NULL, -- Foreign key linking to the Clients table, can be null.
  CONSTRAINT Authentication_pkey PRIMARY KEY (auth_id), -- Primary key constraint on the "auth_id" column.
  CONSTRAINT Authentication_client_id_fkey FOREIGN KEY (client_id) REFERENCES "Clients" (id) -- Foreign key constraint linking "client_id" to "id" in the Clients table.
) TABLESPACE pg_default;

-- The Sessions table handles session management for client logins.
-- It tracks session creation, expiration, and last activity timestamps, ensuring time-limited and secure access.
-- Each session is uniquely identified and linked to a client via a foreign key.
CREATE TABLE public."Sessions" (
  ssesion_id TEXT NOT NULL, -- Primary key for the Sessions table, a unique identifier for the session.
  client_id BIGINT NULL, -- Foreign key linking to the Clients table, can be null.
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), -- Timestamp for when the session was created, defaults to the current time.
  expires_at TIMESTAMP WITH TIME ZONE NULL, -- Timestamp for when the session expires, can be null.
  last_activity TIMESTAMP WITH TIME ZONE NULL, -- Timestamp for the last activity in the session, can be null.
  CONSTRAINT Sessions_pkey PRIMARY KEY (ssesion_id), -- Primary key constraint on the "ssesion_id" column.
  CONSTRAINT Sessions_client_id_fkey FOREIGN KEY (client_id) REFERENCES "Clients" (id) -- Foreign key constraint linking "client_id" to "id" in the Clients table.
) TABLESPACE pg_default;



